<?php

use Illuminate\Database\Seeder;

class GalleriesTableSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (DB::table('galleries')->count() == 0) {
            $galleries = array(
                array('id' => '1', 'product_id' => '1', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '2', 'product_id' => '1', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '3', 'product_id' => '3', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '4', 'product_id' => '3', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '5', 'product_id' => '4', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '6', 'product_id' => '4', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '7', 'product_id' => '5', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '8', 'product_id' => '5', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '9', 'product_id' => '6', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '10', 'product_id' => '6', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '11', 'product_id' => '7', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '12', 'product_id' => '7', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '13', 'product_id' => '8', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '14', 'product_id' => '8', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '15', 'product_id' => '9', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '16', 'product_id' => '9', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '17', 'product_id' => '10', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '18', 'product_id' => '10', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '19', 'product_id' => '11', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '20', 'product_id' => '11', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '25', 'product_id' => '14', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '26', 'product_id' => '14', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '27', 'product_id' => '15', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '28', 'product_id' => '15', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '29', 'product_id' => '16', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '30', 'product_id' => '16', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '31', 'product_id' => '17', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '32', 'product_id' => '17', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '33', 'product_id' => '18', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '34', 'product_id' => '18', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '35', 'product_id' => '19', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '36', 'product_id' => '19', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '37', 'product_id' => '20', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '38', 'product_id' => '20', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '39', 'product_id' => '21', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '40', 'product_id' => '21', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '41', 'product_id' => '22', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '42', 'product_id' => '22', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '43', 'product_id' => '23', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '44', 'product_id' => '23', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '45', 'product_id' => '24', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '46', 'product_id' => '24', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '47', 'product_id' => '25', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '48', 'product_id' => '25', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '49', 'product_id' => '26', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '50', 'product_id' => '26', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '51', 'product_id' => '27', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '52', 'product_id' => '27', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '55', 'product_id' => '28', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '56', 'product_id' => '28', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '61', 'product_id' => '30', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '62', 'product_id' => '30', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '63', 'product_id' => '30', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '64', 'product_id' => '30', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '65', 'product_id' => '31', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '66', 'product_id' => '31', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '67', 'product_id' => '31', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '68', 'product_id' => '31', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '69', 'product_id' => '32', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '70', 'product_id' => '32', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '71', 'product_id' => '32', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '72', 'product_id' => '32', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '73', 'product_id' => '33', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '74', 'product_id' => '33', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '75', 'product_id' => '33', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '76', 'product_id' => '33', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '77', 'product_id' => '34', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '78', 'product_id' => '34', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '79', 'product_id' => '34', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '80', 'product_id' => '34', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '81', 'product_id' => '35', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '82', 'product_id' => '35', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '83', 'product_id' => '35', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '84', 'product_id' => '35', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '85', 'product_id' => '36', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '86', 'product_id' => '36', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '87', 'product_id' => '36', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '88', 'product_id' => '36', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '89', 'product_id' => '37', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '90', 'product_id' => '37', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '91', 'product_id' => '37', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '92', 'product_id' => '37', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '93', 'product_id' => '38', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '94', 'product_id' => '38', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '95', 'product_id' => '38', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '96', 'product_id' => '38', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '117', 'product_id' => '29', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '118', 'product_id' => '29', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '119', 'product_id' => '29', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '120', 'product_id' => '29', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '125', 'product_id' => '40', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '126', 'product_id' => '40', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '127', 'product_id' => '40', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '128', 'product_id' => '40', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '137', 'product_id' => '39', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '138', 'product_id' => '39', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '139', 'product_id' => '39', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '140', 'product_id' => '39', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '165', 'product_id' => '41', 'image' => 'http://luongnd2286.xyz/userfiles/images/smartna999-beptotx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '166', 'product_id' => '41', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_bep-gas-am-rinnai-rvb-212bgx500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '167', 'product_id' => '41', 'image' => 'http://luongnd2286.xyz/userfiles/images/large_may-say-bat-malloca-zld-90-ix500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL),
                array('id' => '168', 'product_id' => '41', 'image' => 'http://luongnd2286.xyz/userfiles/images/bo-noi-chefs-eh-cw4304x500x500x4.webp', 'created_at' => NULL, 'updated_at' => NULL)
            );
            DB::table('galleries')->insert($galleries);
        }
    }
}
